enyo.depends(
	"source/InputSample.js",
	"css/InputSample.css",
	"source/HeaderView.js",
	"source/ViewItem.js",
	"source/Main.js",
	"source/input/KeyPresses.js",
	"source/input/ScreenMovement.js",
	"source/input/Gestures.js",
	"source/input/Multitouch.js"
);